config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  resources :cats
  resources :toys
end

app/models/cat.rb
class Cat < ActiveRecord::Base

  has_many :toys

end

app/models/toy.rb
class Toy < ActiveRecord::Base

  belongs_to :cat

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

  def index
    @toys = Toy.all
  end

  def show
    @toy = Toy.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/index.html.erb
<div class="page-header">
  <h1>Cats!</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>
        Name
      </th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td>
          <%= link_to cat.name, cat_path(cat) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cats/show.html.erb
<div class="page-header">
  <h1><%= @cat.name %></h1>
</div>

<h3>This cat's toys are...</h3>

<div class="well">
  <% @cat.toys.each do |toy| %>
    <li><%= toy.name %></li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>gSchool Rails has_many / belongs_to</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">gSchool</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Cats", cats_path %></li>
            <li><%= link_to "Toys", toys_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="starter-template">
  <h1>Cats and Toys!</h1>
  <p class="lead">Users <strong><em>need</em></strong> to see which toys belong to which cats.</p>
</div>

app/views/toys/index.html.erb
<div class="page-header">
  <h1>Toys!</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th> Toy Name </th>
      <th> Cat </th>
    </tr>
  </thead>
  <tbody>
    <% @toys.each do |toy| %>
      <tr>
        <td>
          <%= link_to toy.name, toy_path(toy) %>
        </td>
        <td>
          <%= link_to toy.cat.name, toy.cat %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/toys/show.html.erb
<div class="page-header">
  <h1><%= @toy.name %></h1>
</div>

<h3>This toy belongs to...</h3>

<div class="well">
  <%= @toy.cat.name %>
</div>